apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rigup-ingress
  namespace: rigup
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2m
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rigup.example.com
      secretName: rigup-tls
  rules:
    - host: rigup.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: core-api
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
