apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rigup
resources:
  - namespace.yaml
  - mysql.yaml
  - core-api.yaml
  - agent-worker.yaml
  - frontend.yaml
  - ingress.yaml
  - agent-worker-hpa.yaml
